- Target: nmaguiar/imgutils:build-lite (alpine 3.22.0_alpha20250108)
  Class: os-pkgs
  Type: alpine
- Target: usr/bin/crictl
  Class: lang-pkgs
  Type: gobinary
  Vulnerabilities:
  - VulnerabilityID: CVE-2024-45338
    PkgID: golang.org/x/net@v0.30.0
    PkgName: golang.org/x/net
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/net@v0.30.0
      UID: 9ce1984a5172bc7c
    InstalledVersion: v0.30.0
    FixedVersion: 0.33.0
    Status: fixed
    Layer:
      Digest: sha256:1747d1109d8c8160a4c05719ff9e47933915757c23be0f9b84b8ff4adabe227e
      DiffID: sha256:eed7b4f50e61a800d30f0d5fe27eac60b38f5508e752fc85a0fd7418cd6fc13f
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45338
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'golang.org/x/net/html: Non-linear parsing of case-insensitive content in golang.org/x/net/html'
    Description: An attacker can craft an input to the Parse functions that would be processed non-linearly with respect to its length, resulting in extremely slow parsing. This could cause a denial of service.
    Severity: HIGH
    CweIDs:
    - CWE-1333
    VendorSeverity:
      amazon: 3
      azure: 3
      cbl-mariner: 3
      ghsa: 3
      redhat: 3
      ubuntu: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H
        V3Score: 7.5
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45338
    - https://cs.opensource.google/go/x/net
    - https://github.com/golang/go/issues/70906
    - https://go-review.googlesource.com/c/net/+/637536
    - https://go.dev/cl/637536
    - https://go.dev/issue/70906
    - https://groups.google.com/g/golang-announce/c/wSCRmFnNmPA/m/Lvcd0mRMAwAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45338
    - https://pkg.go.dev/vuln/GO-2024-3333
    - https://security.netapp.com/advisory/ntap-20250221-0001/
    - https://ubuntu.com/security/notices/USN-7197-1
    - https://www.cve.org/CVERecord?id=CVE-2024-45338
    PublishedDate: '2024-12-18T21:15:08.173Z'
    LastModifiedDate: '2025-02-21T18:15:17.717Z'
  - VulnerabilityID: CVE-2025-22870
    PkgID: golang.org/x/net@v0.30.0
    PkgName: golang.org/x/net
    PkgIdentifier:
      PURL: pkg:golang/golang.org/x/net@v0.30.0
      UID: 9ce1984a5172bc7c
    InstalledVersion: v0.30.0
    FixedVersion: 0.36.0
    Status: fixed
    Layer:
      Digest: sha256:1747d1109d8c8160a4c05719ff9e47933915757c23be0f9b84b8ff4adabe227e
      DiffID: sha256:eed7b4f50e61a800d30f0d5fe27eac60b38f5508e752fc85a0fd7418cd6fc13f
    SeveritySource: ghsa
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22870
    DataSource:
      ID: ghsa
      Name: GitHub Security Advisory Go
      URL: https://github.com/advisories?query=type%3Areviewed+ecosystem%3Ago
    Title: 'golang.org/x/net/http/httpproxy: golang.org/x/net/proxy: HTTP Proxy bypass using IPv6 Zone IDs in golang.org/x/net'
    Description: Matching of hosts against proxy patterns can improperly treat an IPv6 zone ID as a hostname component. For example, when the NO_PROXY environment variable is set to "*.example.com", a request to "[::1%25.example.com]:80` will incorrectly match and not be proxied.
    Severity: MEDIUM
    VendorSeverity:
      ghsa: 2
      redhat: 2
    CVSS:
      redhat:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:L
        V3Score: 4.4
    References:
    - http://www.openwall.com/lists/oss-security/2025/03/07/2
    - https://access.redhat.com/security/cve/CVE-2025-22870
    - https://go-review.googlesource.com/q/project:net
    - https://go.dev/cl/654697
    - https://go.dev/issue/71984
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22870
    - https://pkg.go.dev/vuln/GO-2025-3503
    - https://www.cve.org/CVERecord?id=CVE-2025-22870
    PublishedDate: '2025-03-12T19:15:38.31Z'
    LastModifiedDate: '2025-03-12T19:15:38.31Z'
  - VulnerabilityID: CVE-2024-45336
    PkgID: stdlib@v1.23.3
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.3
      UID: c32ee6844a95cf7d
    InstalledVersion: v1.23.3
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:1747d1109d8c8160a4c05719ff9e47933915757c23be0f9b84b8ff4adabe227e
      DiffID: sha256:eed7b4f50e61a800d30f0d5fe27eac60b38f5508e752fc85a0fd7418cd6fc13f
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45336
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: net/http: net/http: sensitive headers incorrectly sent after cross-domain redirect'
    Description: The HTTP client drops sensitive headers after following a cross-domain redirect. For example, a request to a.com/ containing an Authorization header which is redirected to b.com/ will not send that header to b.com. In the event that the client received a subsequent same-domain redirect, however, the sensitive headers would be restored. For example, a chain of redirects from a.com/, to b.com/1, and finally to b.com/2 would incorrectly send the Authorization header to b.com/2.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 2
      bitnami: 2
      cbl-mariner: 3
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N
        V3Score: 5.9
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45336
    - https://go.dev/cl/643100
    - https://go.dev/issue/70530
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45336
    - https://pkg.go.dev/vuln/GO-2025-3420
    - https://security.netapp.com/advisory/ntap-20250221-0003/
    - https://www.cve.org/CVERecord?id=CVE-2024-45336
    PublishedDate: '2025-01-28T02:15:28.807Z'
    LastModifiedDate: '2025-02-21T18:15:17.4Z'
  - VulnerabilityID: CVE-2024-45341
    PkgID: stdlib@v1.23.3
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.3
      UID: c32ee6844a95cf7d
    InstalledVersion: v1.23.3
    FixedVersion: 1.22.11, 1.23.5, 1.24.0-rc.2
    Status: fixed
    Layer:
      Digest: sha256:1747d1109d8c8160a4c05719ff9e47933915757c23be0f9b84b8ff4adabe227e
      DiffID: sha256:eed7b4f50e61a800d30f0d5fe27eac60b38f5508e752fc85a0fd7418cd6fc13f
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2024-45341
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'golang: crypto/x509: crypto/x509: usage of IPv6 zone IDs can bypass URI name constraints'
    Description: A certificate with a URI which has a IPv6 address with a zone ID may incorrectly satisfy a URI name constraint that applies to the certificate chain. Certificates containing URIs are not permitted in the web PKI, so this only affects users of private PKIs which make use of URIs.
    Severity: MEDIUM
    VendorSeverity:
      amazon: 2
      bitnami: 2
      cbl-mariner: 2
      redhat: 1
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
        V3Score: 6.1
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:H/PR:L/UI:N/S:U/C:L/I:L/A:N
        V3Score: 4.2
    References:
    - https://access.redhat.com/security/cve/CVE-2024-45341
    - https://go.dev/cl/643099
    - https://go.dev/issue/71156
    - https://groups.google.com/g/golang-dev/c/CAWXhan3Jww/m/bk9LAa-lCgAJ
    - https://groups.google.com/g/golang-dev/c/bG8cv1muIBM/m/G461hA6lCgAJ
    - https://nvd.nist.gov/vuln/detail/CVE-2024-45341
    - https://pkg.go.dev/vuln/GO-2025-3373
    - https://security.netapp.com/advisory/ntap-20250221-0004/
    - https://www.cve.org/CVERecord?id=CVE-2024-45341
    PublishedDate: '2025-01-28T02:15:29.147Z'
    LastModifiedDate: '2025-02-21T18:15:17.96Z'
  - VulnerabilityID: CVE-2025-22866
    PkgID: stdlib@v1.23.3
    PkgName: stdlib
    PkgIdentifier:
      PURL: pkg:golang/stdlib@v1.23.3
      UID: c32ee6844a95cf7d
    InstalledVersion: v1.23.3
    FixedVersion: 1.22.12, 1.23.6, 1.24.0-rc.3
    Status: fixed
    Layer:
      Digest: sha256:1747d1109d8c8160a4c05719ff9e47933915757c23be0f9b84b8ff4adabe227e
      DiffID: sha256:eed7b4f50e61a800d30f0d5fe27eac60b38f5508e752fc85a0fd7418cd6fc13f
    PrimaryURL: https://avd.aquasec.com/nvd/cve-2025-22866
    DataSource:
      ID: govulndb
      Name: The Go Vulnerability Database
      URL: https://pkg.go.dev/vuln/
    Title: 'crypto/internal/nistec: golang: Timing sidechannel for P-256 on ppc64le in crypto/internal/nistec'
    Description: Due to the usage of a variable time instruction in the assembly implementation of an internal function, a small number of bits of secret scalars are leaked on the ppc64le architecture. Due to the way this function is used, we do not believe this leakage is enough to allow recovery of the private key when P-256 is used in any well known protocols.
    Severity: MEDIUM
    VendorSeverity:
      bitnami: 2
      redhat: 2
    CVSS:
      bitnami:
        V3Vector: CVSS:3.1/AV:L/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
        V3Score: 4
      redhat:
        V3Vector: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N
        V3Score: 5.3
    References:
    - https://access.redhat.com/security/cve/CVE-2025-22866
    - https://go.dev/cl/643735
    - https://go.dev/issue/71383
    - https://groups.google.com/g/golang-announce/c/xU1ZCHUZw3k
    - https://nvd.nist.gov/vuln/detail/CVE-2025-22866
    - https://pkg.go.dev/vuln/GO-2025-3447
    - https://security.netapp.com/advisory/ntap-20250221-0002/
    - https://www.cve.org/CVERecord?id=CVE-2025-22866
    PublishedDate: '2025-02-06T17:15:21.41Z'
    LastModifiedDate: '2025-02-21T18:15:32.243Z'
