name: Version Images

on:
  workflow_dispatch:
  schedule:
    - cron: '37 3 * * 6'

jobs:
  Version-Images:
    runs-on    : ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name       : Version images
    steps      :
    - uses: actions/checkout@v4
      name: Checkout

    - name: Cache OpenAF runtime
      uses: actions/cache@v3
      with:
        key : oaf-nightly
        path: /tmp/oaf

    - name: Generate build versions badge
      uses: openaf/ojob-action@v7
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: '.github/ojobs/getVersions.yaml'
        args: 'tag=build file=.github/build-versions.svg jsonfile=.github/build-versions.json'
        dist: 'nightly'

    - name: Generate latest versions badge
      uses: openaf/ojob-action@v7
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: '.github/ojobs/getVersions.yaml'
        args: 'tag=latest file=.github/latest-versions.svg jsonfile=.github/latest-versions.json'
        dist: 'nightly'

    - uses: openaf/ojob-action@v7
      name: Update badges
      env :
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ojob: 'ojob.io/git/hub/contentIn'
        args: 'message="update\ badge\ {{date}}/{{time}}" title="Update\ badge" paths=.github/'
        dist: 'nightly'
